api_key:
  key: "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"
model:
  name:   "gpt-4o-mini"    # "gpt-4o-mini" "gpt-4o"  "gpt-3.5-turbo"  "o3-mini" "o1-mini"